### ISSUE TITLE
Comments on possible experiments

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#28]
Is this the focus of the paper? Can we mention preliminary results?

**Comment by unintendedbear** [comment]
Where do we include this?

I'm going to include statistics like "n. of events per day" to justify the use of big data techniques. But I guess this issue is more related to something like "the number of security violations significantly decreased  in verbose mode". But then we should explain what's silent mode and what's verbose mode.

And again, where in the paper is best to put this?

**Comment by amorag** [comment]
En mi opinión:
- Si se van a incluir datos de las pruebas realizadas hasta el momento (lo de las Trials y demás) lo metería al final de la sección 4 (la de descripción de MUSES), en una nueva sección (4.4). Eso le daría más peso al trabajo y al sistema que se presenta.
- Si son posibles experimentos o pruebas a realizar, pero que no se incluirán en este trabajo (por falta de datos, de tiempo, de espacio), lo pondría en la parte de trabajo futuro (al final de las conclusiones).

**Comment by amorag** [comment]
Lo he movido a una sección aparte (4.4) para que destaque más, ya que los revisores

He metido un poco más de texto para presentarlo y demás.

Echadle un ojo al commit 16bf3e758607481f07b570eef9f63208b78d7573
