### ISSUE TITLE
Include to which class of the taxonomy every reviewed tool belongs to

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems#44]
According to what's described.

**Comment by amorag** [comment]
Por favor, incluye (o incluid, junto con @fergunet) un texto explícito sobre la categoría de cada herramienta en la taxonomía. Ahora mismo es difícil encontrarlo y habría que justificarlo bien ante los revisores.

Podéis ponerlo siempre al final de la sección de cada herramienta, si lo veis oportuno, o en medio de su descripción, pero haced referencia a algo como "this tool is enclosed in category X of the taxonomy, because...".

Si lo ponéis al final será más fácil justificarlo en las respuestas.

En MUSES podéis decirlo cuando mejor creáis y simplemente se señala en la respuesta en qué página y párrafo se ha puesto.

La tabla creo que es un buen complemento como resumen, pero creo que un texto explicativo en cada sección sería recomendable.
No sé qué opinan @JJ y @pacastillo

Gracias.

**Comment by unintendedbear** [comment]
Ayer estuve incluyendo esas explicaciones precisamente, porque al ponerme a rellenarle la tabla a @deantares, alguna info la podía sacar del texto de descripción pero la que me faltaba y tuve que buscar, la añadí a las descripciones, con referencias a la documentación y todo. Incluso comenté que para el blackphone no se podían saber muchas cosas.

**Comment by amorag** [comment]
La verdad es que es difícil encontrarlo al estar dentro del resto de la descripción, por eso decía que lo pusiéseis explícitamente. Si puedes poner la coletilla o el término 'taxonomy' en las frases correspondientes les será más fácil a los revisores.

O indica en las respuestas en qué páginas y párrafos están esas descripciones, como prefieras.

Gracias.

**Comment by unintendedbear** [comment]
Moar opiniones needed, lo he releído y lo veo bien así :\

**Comment by amorag** [comment]
Si lo ves bien, entonces simplemente señala las páginas y párrafos en los que se comenta eso para cada herramienta en la respuesta al  revisor #4:
- respuesta a los cambios de la sección 3, punto 2)

**Comment by unintendedbear** [comment]
Sí, he cerrado 3 issues que estaban hechos y no cerrados. Pido perdón a @JJ de corazón, pero como abra el .tex otra vez me echo a llorar de cansancio.

**Comment by JJ** [comment]
:-)

El 9 de julio de 2015, 19:56, Paloma de las Cuevas Delgado <
notifications@github.com> escribió:

> Sí, he cerrado 3 issues que estaban hechos y no cerrados. Pido perdón a
> @JJ https://github.com/JJ de corazón, pero como abra el .tex otra vez
> me echo a llorar de cansancio.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2014-2015-COMCOM-MUSES_vs_SotA_BYOD_Systems/issues/44#issuecomment-120086938
> .

## 

JJ
